env:
  es6: true
  node: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 6
  ecmaFeatures:
    experimentalObjectRestSpread: true
rules:
  prettier/prettier:
    - error
    - singleQuote: true
    - trailingComma: 'all'
  no-unused-vars:
    - error
    - vars: 'all'
  no-undef:
    - error
